### PR TITLE
Support builds starting with 222.*

### PR DESCRIPTION
**Pull request by chbndrhnns**

### CODE REVIEW

**Comment by koxudaxi** [comment]
@chbndrhnns 
Thank you for creating this PR.
I tested the PR with `222.2270.35-EAP-SNAPSHOT`.
But, I got two errors.
Could you check it?
If I can get the time then I will check it.
Screenshot 2022-05-31 at 10 27 25

**Comment by chbndrhnns** [comment]
I am running the same version of PyCharm locally and loaded a compiled version of the plugin there.
However, I built the plugin using IntelliJ 2022.1.1 and the 75 tests pass when I run them there.

Do we have a different setup in some aspect?

**Comment by chbndrhnns** [comment]
I was missing the correct `platformVersion`. Now I also see two failing tests.
It's the first time I ever look at the plugin code so I am not sure I can resolve the issues by myself.

**Comment by KotlinIsland** [comment]
This can be closed

**Pull request closed without merging**
