### PR TITLE
Support 241 EAP

### PR DESCRIPTION
**Pull request by koxudaxi**
Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/876

### CODE REVIEW

**Comment by skewty** [comment]
Any chance a new build will go out anytime soon? I'd like to try out 2024.1 EAP and this plugin is holding me back since you already released your updated Ruff plugin.

**Comment by koxudaxi** [comment]
@skewty 

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/887
Sorry, I have not been able to release it.
As you can see in this issue, unittest is an error in the latest EAP.
The worst-case scenario is removing and releasing the unittest, but we would like to fix it if possible. (unittest is a must since API changes are made with every version upgrade)

I also asked a question on the Slack community here, but I didn't get any reply!:sweat: 
https://plugins.jetbrains.com/slack/

**Comment by koxudaxi** [comment]
Sorry for the delay.
I have released a corresponding version 0.4.12

This is due to a workaround of commenting out the unittest, not solving the cause.

**Comment by skewty** [comment]
> Sorry for the delay.
2024.1 isn't even out yet! Your sorry is too much.
But thank you, again!

**Pull request merged**
